### ISSUE TITLE
Skylight gem fails in rails 6.1

### ISSUE THREAD

**Issue by andrewhttr** [skylightio/skylight-ruby#163]
When trying to load the site under development. You get a 500 error.

**Comment by wagenet** [comment]
Sorry for the trouble. I believe this should be fixed in the 5.x beta series.

**Comment by andrewhttr** [comment]
No worries just letting you know.

**Comment by jeremiemv** [comment]
Hitting the same issue

`NoMethodError (undefined method `instrument' for #<ActionView::TemplateRenderer:0x00007f9d9cc61ee8>):`

**Comment by Aeramor** [comment]
Same issue here!

**Comment by wagenet** [comment]
@jeremiemv @Aeramor have you tried the beta?

**Comment by jeremiemv** [comment]
@wagenet not yet

**Comment by jeremiemv** [comment]
@wagenet the beta fixed the issue. Tests are green and app us running locally.

**Comment by JulianRamirez** [comment]
In the meanwhile, you can comment out the offending probe in your `application.rb`, just be sure to remove this line once the beta is on the main channel:

> `config.skylight.probes -= %w[action_view]`

**Comment by breisig** [comment]
This issue is pretty big.

**Comment by wagenet** [comment]
@breisig This is fixed in 5.x and in 4.3.2 which was released a month ago. We should have closed it.
