### PR TITLE
Fix Ruby 2.4 build failure due to treating extra semicolon warning as error

### PR DESCRIPTION
**Pull request by jeremy**
Extra parens introduced in https://github.com/ruby/ruby/commit/28f5e12c24edda376c863090c09406185373167b for a macro.

Causes skylight build failure since it treats the warning as an error:
```
compiling skylight_memprof.c
In file included from skylight_memprof.c:1:
In file included from /Users/jeremy/.rbenv/versions/2.4.0-dev/include/ruby-2.4.0/ruby.h:33:
In file included from /Users/jeremy/.rbenv/versions/2.4.0-dev/include/ruby-2.4.0/ruby/ruby.h:1998:
/Users/jeremy/.rbenv/versions/2.4.0-dev/include/ruby-2.4.0/ruby/intern.h:485:34: error: extra ';' outside of a function [-Werror,-Wextra-semi]
PUREFUNC(int rb_during_gc(void););
                                 ^
/Users/jeremy/.rbenv/versions/2.4.0-dev/include/ruby-2.4.0/ruby/intern.h:787:41: error: extra ';' outside of a function [-Werror,-Wextra-semi]
PUREFUNC(size_t rb_str_capacity(VALUE););
                                        ^
2 errors generated.
make: *** [skylight_memprof.o] Error 1

make failed, exit code 2
```

Set `-Wno-error=extra-semi` to suppress the error.

### CODE REVIEW

**Comment by jeremy** [comment]
This is a clang-only warning, so gcc is gonna complain. Not sure how to mollify them both.

**Comment by chancancode** [comment]
Thanks for catching this @jeremy! Before we can merge it, can I ask you to sign the [CLA](https://docs.google.com/forms/d/16ygxA3DUxHh3Q7KHGtzy5qcbcbRs1od93fgXByk8m-g/viewform?formkey=dHJVY1M5bzNzY0pwN2dRZjMxV0dXSkE6MA#gid=0)?

For the gcc/clang difference, I guess we would need to look into how to emit a compiler id check into the Makefile generated by extconf. 😕 (If you happen to know/find a way, please let us know!)

**Comment by wagenet** [comment]
Hmm... this kills our Travis build. While I'm inclined to trust you on this being a good idea, I'd need to find a way to avoid the Travis problems.

**Comment by jeremy** [comment]
Yep, this fixes clang (since it won't error on that warning anymore) and
breaks GCC (since it doesn't recognize the flag).

Waiting is a good option too. Upstream Ruby will probably change the code
so users aren't exposed to the warning.

**Comment by chancancode** [comment]
@jeremy this should be fixed on Ruby truck as of https://github.com/ruby/ruby/commit/fd25eea0e4c1965a4e199317547ec47f4d8f1b93. Let me know if that fixed the issue for you!

**Comment by jeremy** [comment]
Sure does 👍
