### ISSUE TITLE
Multiple environments not working in 3.0.0

### ISSUE THREAD

**Issue by kapso** [skylightio/skylight-ruby#128]
Tried multiple environments with v3.0.0 but I get this error in Rails 5.2.0 app

https://www.skylight.io/support/environments

```
`method_missing': undefined method `skylight' for #<Rails::Application::Configuration:0x00007ffd01c55188> (NoMethodError)

```

**Comment by zvkemp** [comment]
Hi @kapso, thanks for the report. Can you please provide a complete backtrace for the error you're seeing?

**Comment by kapso** [comment]
@zvkemp 

```
/Users/kapil/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `skylight' for #<Rails::Application::Configuration:0x00007ffd01c55188> (NoMethodError)
	from /Users/kapil/projects/wheels/config/application.rb:28:in `<class:Application>'
	from /Users/kapil/projects/wheels/config/application.rb:10:in `<module:Wheels>'
	from /Users/kapil/projects/wheels/config/application.rb:9:in `<top (required)>'
	from /Users/kapil/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /Users/kapil/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /Users/kapil/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/kapil/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/kapil/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/kapil/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/kapil/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/kapil/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/kapil/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'
```

**Comment by zvkemp** [comment]
Thanks @kapso. What are you invoking on `/Users/kapil/projects/wheels/config/application.rb:28`?

**Comment by kapso** [comment]
@zvkemp think I mentioned that above, but here you go

<img width="1030" alt="screen shot 2018-09-05 at 2 46 08 pm" src="https://user-images.githubusercontent.com/344198/45123062-8ac17380-b11a-11e8-81cf-a775b942d61c.png">

**Comment by zvkemp** [comment]
Do you have `skylight` in a bundler group for a specific environment? If you have it in production but not development, this is probably the first error you would encounter.

**Comment by kapso** [comment]
Of course I do :( sorry! my bad thats embarrassing, I am used to using Skylight in prod only :)

Thanks that fixes it.
